### PR TITLE
Create new manifest repo

### PR DESCRIPTION
**Pull request by Stefan-Schmidt**
This will hold a fork of the OpenHarmony mirror manifest for our enhancements and fixes.

### CODE REVIEW

**Review by netomi — APPROVED** [review]

**Comment by netomi** [comment]
repo has been created.

**Comment by Stefan-Schmidt** [comment]
@netomi I have a quick follow up question on this.
Otterdog does initialize the repo with an README.md file commit in main. I now want to push a full existing repo to this new one. (git push --mirror) which works fine for all branches but main. I would need a way to enable force push to main for one time to get this straight.
I looked into the otterdog docs but it did not really became clear to me how I would do this. Would I need to create a branch protection pattern to match and allow the force push and revert the commit afterwards?

**Comment by netomi** [comment]
to prevent such cases you can set the auto_init flag to false when create a new repo.

There is no branch protection rule defined for the repo, so everyone with push permissions should be able to force push to it afaict.

**Comment by netomi** [comment]
ftr. the original manifest repo at https://github.com/eclipse-oniro-mirrors/manifest does not have a main branch.

There is a master branch though.

**Comment by Stefan-Schmidt** [comment]
> to prevent such cases you can set the auto_init flag to false when create a new repo.

Thanks for the auto_init hint. That will become handy in the future.

> There is no branch protection rule defined for the repo, so everyone with push permissions should be able to force push to it afaict.

I see. Digging a bit deeper the issue might indeed just be the main branch. --mirror is trying to remove it (as it does not exist on the original repo) but given it is set as default branch the removal is rejected. I suppose changing the default branch away from main will solve this issue. Will raise a PR for this. Thanks for the support.

**Pull request merged**
