### PR TITLE
otterdog: enable force push to remove repo README init commit

### PR DESCRIPTION
**Pull request by Stefan-Schmidt**
This init repo commit does conflict with project history. Allow force push to remove it and switch back afterwards.

### CODE REVIEW

**Comment by netomi** [comment]
if the repo should have been creates as fork this is also possible by specifying: forked_repository: xxx
alternatively, specifying auto_init: false makes sure the repo is not initialized at all.

I can remove the repo again and we do as you want, but let me know.

**Comment by Stefan-Schmidt** [comment]
> if the repo should have been creates as fork this is also possible by specifying: forked_repository: xxx alternatively, 

Ah, I did not know this is possible. Is this a new otterdog feature? The fork command would only work for github.com repositories, right?

> specifying auto_init: false makes sure the repo is not initialized at all.

Yeah, that was my bad. I forgot about it when creating the repos. :/

> I can remove the repo again and we do as you want, but let me know.

Only one of the two repos is on github, the other is on gitee. So using the fork would only work for one.
For now doing the force push to fix it is fine and I will disable this right after.

For upcoming forks I will definitely keep this in mind. Thanks!

**Comment by netomi** [comment]
the support for creating forks with otterdog is there for a while, but most people are not aware of it.

btw. the change that you made should not enable forced pushes afaict. That should have been possible anyways as there is no branch protection rule defined yet. The setting you changed just enabled an update button in PRs if the branch to be merged is not up-to-date.

**Comment by Stefan-Schmidt** [comment]
> the support for creating forks with otterdog is there for a while, but most people are not aware of it.

Same here. Nice to know, now. :-)

> btw. the change that you made should not enable forced pushes afaict. That should have been possible anyways as there is no branch protection rule defined yet. The setting you changed just enabled an update button in PRs if the branch to be merged is not up-to-date.

That is a bit embarrassing. I did not even think twice that this could mean something else. In any case the branch is force pushed and I reverted the change back to normal.

**Comment by netomi** [comment]
np, was just wondering when I have seen that PR.

**Pull request merged**
